### ISSUE TITLE
"h chaninfo" throws error

### ISSUE THREAD

**Issue by TehPeGaSuS** [tclscripts/BlackTools-TCL#13]
When using `h chaninfo` in PM with the bot, there's no response.

On partyline I get the following:
```
[19:56:43] Tcl error [command:pubpriv]: no such channel record
[19:56:43] [James_Bond!sid116151@id-116151.uxbridge.irccloud.com] h chaninfo
```

**Comment by DanielVoipan** [comment]
Hello, You have to use **h #channel chaninfo** in private. If you don't want to use the channel just set your mychan with **.myset mychan #channel** . Then you can use **h chaninfo** in private because it will be the chaninfo for your mychan.

**Comment by DanielVoipan** [comment]
Solved and updated. Now you can use h chaninfo without channel if have global access.

**Comment by DanielVoipan** [comment]
solved.
