### ISSUE TITLE
antipub and antibadword don't work with emojis

### ISSUE THREAD

**Issue by terren4l** [tclscripts/BlackTools-TCL#14]
when antipub or antibadword is activated on the channel, the bot crashes when users use emojis.

**Comment by DanielVoipan** [comment]
download and compile and use the latest eggdrop from https://ftp.eggheads.org/pub/eggdrop/source/1.9/eggdrop-1.9.5rc1.tar.gz

They solved this issue regarding emoji.

**Comment by terren4l** [comment]
Thank you, it's true, done
