### ISSUE TITLE
Pass & h not working after taking ownership

### ISSUE THREAD

**Issue by ghost** [tclscripts/BlackTools-TCL#6]
I have a bit of a weird issue. I'm a first time user of BlackTools and a long time user of Eggdrop.
I recently did a clean install of the latest stable version of Eggdrop 1.8.
After taking ownership of the bot, I can set a password with the pass command. However, it's no longer possible to use pass to change your password.
Also after taking ownership, the bot isn't responding to .h, !h, @h in the channel, or to h in pmsg window for new users.

**Comment by DanielVoipan** [comment]
hello, please use this tcl : https://tclscripts.net/downloads/debug-tcl/
Setup the channel in it and see if the eggdrop returns some error on that channel when you use .h
